[project]
name = "a2"
version = "0.1.0"
description = "representation learning"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pillow>=12.2.0",
    "scikit-learn>=1.7.2",
    "torch==2.5.0",
    "torchvision>=0.20.0",
    "tqdm>=4.67.3",
    "wandb>=0.26.0",
]

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cuda" }]
torchvision = [{ index = "pytorch-cuda" }]
torchaudio = [{ index = "pytorch-cuda" }]
